[tool.poetry]
name = "legisph"
version = "0.1.0"
description = "Legislative Analysis of the Philippines"
authors = ["TJ P <mail@tjpalanca.com>"]
license = "CC BY-NC-ND 4.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
tjutils = "^0.6.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
